# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datree < Formula
  desc ""
  homepage "https://datree.io/"
  version "0.9.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/datreeio/datree/releases/download/0.9.0/datree-cli_0.9.0_Darwin_x86_64.zip"
    sha256 "742a46a52d3dac429e761b49e8355d14337dbc95f449aa6ecd6a6aebf8b53b43"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/datreeio/datree/releases/download/0.9.0/datree-cli_0.9.0_Linux_x86_64.zip"
    sha256 "34a519b149a3a819d8519dd7db897b74e0c52a3549792a84de173c63b02ba874"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/datreeio/datree/releases/download/0.9.0/datree-cli_0.9.0_Linux_arm64.zip"
    sha256 "84ed515c0f6683c722ead077de29bf564178e398e033eb81a3f40ebe7dcb2c8a"
  end

  def install
    bin.install "datree"
  end
end
