# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datree < Formula
  desc ""
  homepage ""
  version "0.6.4-DAT-3371-homebrew"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/datreeio/datree/releases/download/0.6.4-DAT-3371-homebrew/datree-cli_0.6.4-DAT-3371-homebrew_Darwin_x86_64.zip"
    sha256 "0b708af74c6a8fc2af841e10c640aa1f1ab56d7fb2a9a56ff38f1ae86170194e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/datreeio/datree/releases/download/0.6.4-DAT-3371-homebrew/datree-cli_0.6.4-DAT-3371-homebrew_Linux_x86_64.zip"
    sha256 "51b6c042de4720a5c2e3f799e4d476af3f5950742bc5be779583d92e46eaf320"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/datreeio/datree/releases/download/0.6.4-DAT-3371-homebrew/datree-cli_0.6.4-DAT-3371-homebrew_Linux_arm64.zip"
    sha256 "46f456c2fbff3739eba72c1056fc0ece5afa7bcc05ac110ed947da293b29aa8a"
  end

  def install
    bin.install "datree-cli"
  end
end
